### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by IanPennebaker** [itglue/automation#27]
I am completely lost. Here is my very simple code. 
`
$data = @{

        type = "flexible-assets"

        attributes = @{

            organization_id = xxxxx #Left out intentionally

            flexible_asset_type_id = xxxxx #Left out intentionally

            traits = @{

                name = "Test"

                location = "Home"

            }

        }

}

$output = New-ITGlueFlexibleAssets -data (ConvertTo-Json $data)
`

And here is the error I get:
`
New-ITGlueFlexibleAssets : The remote server returned an error: (500) Internal Server Error.
At line:1 char:11
+ $Output = New-ITGlueFlexibleAssets
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-ITGlueFlexibleAssets
`

Does anyone have any idea? Thanks in advanced.

**Comment by IanPennebaker** [comment]
I have left out the org id and asset type id intentionally.

**Comment by CalebAlbers** [comment]
Hey @IanPennebaker,

The `New-ITGlueFlexibleAssets` function already takes care of the JSON conversion for you, so you shouldn't need to use the `ConvertTo-Json` function. Can you try without it and let me know what response you get? You should just be able to run:
```powershell
$output = New-ITGlueFlexibleAssets -data $data
```

**Comment by IanPennebaker** [comment]
Hey @CalebAlbers 

I removed the ConvertTo-JSON and am now getting the following error:
'
New-ITGlueFlexibleAssets : {"errors":[{"status":401,"title":"Unauthorized","detail":"Unauthorized resource access","source":{"pointer":"id"}}]}
At line:12 char:11
+ $output = New-ITGlueFlexibleAssets -data $data
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-ITGlueFlexibleAssets
'

**Comment by IanPennebaker** [comment]
SOLVED

My "location" field had to take the location ID rather than name.
