### ISSUE TITLE
How can I use checklist API ?

### ISSUE THREAD

**Issue by mzahirr** [itglue/automation#34]
Hi I'm trying to use checklist api but I'm getting this error . Could you please help ?

curl --location -g --request GET 'https://api.itglue.com/organizations/{org_id}/relationships/checklists?filter[configuration_type_id]={type_id}' \
--header 'x-api-key: ....
--header 'Content-Type: application/vnd.api+json'

{
    "errors": [
        {
            "status": 401,
            "title": "Only supported for JWT requests",
            "detail": "Unauthorized resource access",
            "source": {
                "pointer": "id"
            }
        }
    ]
}

**Comment by CalebAlbers** [comment]
Hi @mzahirr,

Unfortunately, the checklists API is not [currently public](https://api.itglue.com/developer/). Please reach out to your account manager and put in a feature request, though - that's the fastest way to get it on the roadmap :)
