### ISSUE TITLE
It is possible to get documents with API get request?

### ISSUE THREAD

**Issue by biyro02** [itglue/automation#35]
![Screenshot from 2021-03-03 15-23-47](https://user-images.githubusercontent.com/33553775/109805429-794a7b00-7c34-11eb-8dde-ad408a8a7b0d.png)
Hi,
When I'm researching about your API documentation, I realized that: there is no GET request for documents endpoint. I want to get documents inside to our application like your documents UI. I wonder that, is it possible with your API? Or how can I reach all documents by your API?
Thanks a lot.

**Comment by bagillsumbc** [comment]
Hi,

Did you every figure out a way around this? I'm struggling with this right now.

**Comment by biyro02** [comment]
Hi, sorry we couldn’t figure it out. Unfortunately we gave up this :(

iPhone’umdan gönderildi

Diana Bell ***@***.***> şunları yazdı (28 May 2021 23:11):

**Comment by CalebAlbers** [comment]
Hey @biyro02 and @bagillsumbc!

Unfortunately, IT Glue's API does not currently support documents, other than modifying metadata (such as the name) of existing docs. As soon as it does, I'll be sure to update the [PowerShell Wrapper](https://github.com/itglue/powershellwrapper) with new commands for it.

The best way to help get support for it would be to reach out to your account manager and put in a feature request.

Cheers!
